print("Hello World")
print("What's your name?")
myName = input()
print("It is nice to meet you, "+ myName)
print("The length of your name is: ")
print(len(myName))
print("What is your age")
myAge = input()
print("You will be " + str(int(myAge) + 11) + " in 2031!" )
